services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: pitorrent-transmission
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Bangkok
      - USER=
      - PASS=
    volumes:
      - /mnt/pitorrent/data/transmission:/config
      - /mnt/pitorrent/downloads:/downloads
      - /mnt/pitorrent/data/watch:/watch
    expose:
      - "9091"
    ports:
      - "51413:51413"
      - "51413:51413/udp"

  addon:
    build: ./addon
    container_name: pitorrent-addon
    restart: unless-stopped
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - /mnt/pitorrent/downloads/complete:/downloads/complete:ro
      - /mnt/pitorrent/data/subtitles:/data/subtitles
    expose:
      - "7000"

  web:
    image: nginx:alpine
    container_name: pitorrent-web
    restart: unless-stopped
    depends_on:
      - transmission
      - addon
    ports:
      - "8080:8080"
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /mnt/pitorrent/downloads/complete:/downloads/complete:ro
