[global]
   workgroup = WORKGROUP
   netbios name = PITorrent
   server string = PiTorrent
   server role = standalone server
   map to guest = Bad User
   guest account = nobody
   security = user
   server min protocol = SMB2
   server max protocol = SMB3
   smb ports = 445 139
   disable netbios = no
   name resolve order = bcast host
   load printers = no
   printing = bsd
   printcap name = /dev/null
   log file = /dev/stdout
   logging = file

[PiTorrent]
   path = /share
   browseable = yes
   guest ok = yes
   read only = yes
   writable = no
   force user = nobody
   force group = nobody
